### ISSUE TITLE
APIKEY in dropwizard swagger

### ISSUE THREAD

**Issue by fkaddereit** [smoketurner/dropwizard-swagger#101]
Hi,

I'm trying to make a APIKEY-protected resource available. In Swagger if I click the "Try it out"-Button, I get a 403-Forbidden-Error just as expected. What I'd like to have is that the user gets to fill in his APIKEY. It works for PathParam and I guess QueryParam but my APIKEY hides in the request-header.

I tried inserting securityDefinitions like defined in Swagger 2 in the YAML with APIKeyHeader:
```
swagger:
  resourcePackage: my.packages.def.resources
  securityDefinitions:
    APIKeyHeader:
      type: apiKey
      in: header
      name: myApikeyEntry
```
and then annotating the method:
```
    @ApiOperation(
			value = "my awesome method", 
			notes = "I am api key protected but I don't show it", 
			response = Response.class,
					authorizations = {
							  @Authorization(
									  value="myApikeyEntry")
					  	}
			)
```
which gets me a lock-symbol next to the method in Swagger but that's it. Am I doing something wrong or is the apikey-thing not supported in your implementation, yet?

Thx in advance!
