### ISSUE TITLE
Allow Setting Security and Components through YAML Configuration

### ISSUE THREAD

**Issue by DanyBv** [smoketurner/dropwizard-swagger#335]
It would be beneficial to provide the functionality for configuring the security and components directly via the YAML configuration. This would enable, for instance, the global setting of the security scheme as shown below:
```yml
swagger:
  resourcePackage: my.resource.package
  security:
    - keycloak: []
  components:
    securitySchemes:
      keycloak:
        type: openIdConnect
        openIdConnectUrl: https://my-host/auth/realms/my-realm/.well-known/openid-configuration
  swaggerViewConfiguration:
    showAuth: true
```

Currently, the only way to configure the security scheme globally seems to be by annotating one of the resources as demonstrated in the following snippet:
```java
@OpenAPIDefinition(security = @SecurityRequirement(name = "keycloak"))
@SecurityScheme(name = "keycloak", type = SecuritySchemeType.OPENIDCONNECT, openIdConnectUrl = "...")
```
