### ISSUE TITLE
disable /swagger only

### ISSUE THREAD

**Issue by felixgao** [smoketurner/dropwizard-swagger#63]
I was able to get the endpoint up and running.     I would like to disable the SwaggerResource and only leave /swagger.{json|yaml} in place.
```
GET     /swagger (io.federecio.dropwizard.swagger.SwaggerResource)
GET     /swagger.{type:json|yaml} (io.swagger.jaxrs.listing.ApiListingResource)
```
my config.yml looks like
```
swagger:
  version: 2.0
  resourcePackage: com.test.rest.resource
  enabled: True
```

Thanks.
